In [1]:
import pandas as pd
import statsmodels.api as sm
import math
import numpy as np

In [2]:
reds = pd.read_csv("RED_faults.csv")

In [ ]:
counter = 1
for i in range(len(reds)):
    if reds.vehicle_id[i+1] != reds.vehicle_id[i]:
        counter += 1
    reds["fault_id"][i+1] = counter

display(reds)

In [3]:
display(reds)

,vehicle_id,message_date_time,in_service_dt,vehicle_make,engine_hours,idle_engine_hours,gross_combined_weight,odometer_reading,description,item_value
0,100236451,2022-07-29 13:45:01,2021-01-28 00:00:00,VOLVO,3300.205,774.951,38999.774,124038.180,Ad Blue Level,92
1,100236451,2022-07-29 13:45:01,2021-01-28 00:00:00,VOLVO,3300.205,774.951,38999.774,124038.180,Parking Brake Engaged,off
2,100236451,2022-07-29 13:45:01,2021-01-28 00:00:00,VOLVO,3300.205,774.951,38999.774,124038.180,Engine Exhaust Temperature,606.0875
3,100236451,2022-07-29 13:45:01,2021-01-28 00:00:00,VOLVO,3300.205,774.951,38999.774,124038.180,Time left to Torque Reduction,0.33333
4,100236451,2022-07-29 13:45:01,2021-01-28 00:00:00,VOLVO,3300.205,774.951,38999.774,124038.180,Total vehicle fuel,13579.896437
...,...,...,...,...,...,...,...,...,...,...
84789481,100486811,2022-12-23 04:15:49,2022-01-31 00:00:00,VOLVO,NaN,1537.852,NaN,230989.179,Engine Shutdown,inactive
84789482,100486811,2022-12-23 04:15:49,2022-01-31 00:00:00,VOLVO,NaN,1537.852,NaN,230989.179,Engine Oil Temperature,204.96
84789483,100486811,2022-12-23 04:15:49,2022-01-31 00:00:00,VOLVO,NaN,1537.852,NaN,230989.179,Load Percent,55
84789484,100486811,2022-12-23 04:15:49,2022-01-31 00:00:00,VOLVO,NaN,1537.852,NaN,230989.179,Boost Pressure,11.89309
84789485,100486811,2022-12-23 04:15:49,2022-01-31 00:00:00,VOLVO,NaN,1537.852,NaN,230989.179,Road Speed,52

In [ ]:
reds_pvt = reds.pivot_table(columns = 'description', index = 'vehicle_id', values = 'item_value', aggfunc="mean").reset_index()

In [ ]:
display(reds_pvt)